name: CI/CD

on:
  push:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy Develop
        if: github.ref == 'refs/heads/develop'
        uses: akhileshns/heroku-deploy@v3.9.9
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: 'dev-api-peliculas'
          heroku_email: 'teamreact17@gmail.com'
          team: 'Team-React-17'
          branch: 'develop'

      - name: Deploy Production
        if: github.ref == 'refs/heads/master'
        uses: akhileshns/heroku-deploy@v3.9.9
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: 'prod-api-peliculas'
          heroku_email: 'teamreact17@gmail.com'
          team: 'Team-React-17'
          branch: 'master'
