name: CI/CD

on:
  push:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        if: github.ref == 'refs/heads/develop'
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache dependencies
        if: github.ref == 'refs/heads/develop'
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        if: github.ref == 'refs/heads/develop'
        run: npm install

      - name: set env REACT_APP_HOST_API
        if: github.ref == 'refs/heads/develop'
        run: export REACT_APP_HOST_API=${{secrets.REACT_APP_HOST_API}}

      - name: set env REACT_APP_PATH_USER
        if: github.ref == 'refs/heads/develop'
        run: export REACT_APP_PATH_USER=${{secrets.REACT_APP_PATH_USER}}

      - name: Build
        if: github.ref == 'refs/heads/develop'
        run: npm run build

      - name: Deploy Develop
        if: github.ref == 'refs/heads/develop'
        run: |
          git config --global user.name $user_name
          git config --global user.email $user_email
          git remote set-url origin https://${github_token}@github.com/${repository}
          npm run deploy
        env:
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          github_token: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
          repository: ${{ github.repository }}

      - name: Deploy Production
        if: github.ref == 'refs/heads/master'
        uses: akhileshns/heroku-deploy@v3.9.9
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: 'prod-api-peliculas'
          heroku_email: 'teamreact17@gmail.com'
          team: 'Team-React-17'
          branch: 'master'
